# Generated by Django 3.2.6 on 2021-08-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome do paciente')),
                ('cpf', models.CharField(max_length=250, verbose_name='Informe seu CPF ')),
                ('grupo_prioritario', models.IntegerField(choices=[(1, 'Pessoas com 60 anos ou mais institucionalizadas'), (2, 'Pessoas com Deficiência Institucionalizadas'), (3, 'Povos indígenas Vivendo em Terras Indígenas'), (4, 'Trabalhadores de Saúde'), (5, 'Pessoas de 90 anos ou mais'), (6, 'Profissionais da educação')], verbose_name='Informe o grupo Prioritário')),
                ('rg', models.CharField(blank=True, max_length=250, null=True, verbose_name='RG')),
                ('cns', models.CharField(blank=True, max_length=250, null=True, verbose_name='Núme. CNS')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10, verbose_name='Sexo')),
                ('data_nascimento', models.DateTimeField(verbose_name='Data Nascimento')),
                ('celular', models.CharField(max_length=250, verbose_name='Núm. celular')),
                ('cep', models.CharField(blank=True, max_length=250, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=250, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=250, null=True, verbose_name='Número')),
                ('bairro', models.CharField(max_length=250, verbose_name='Bairro')),
                ('uf', models.CharField(max_length=250, verbose_name='UF')),
                ('cidade', models.CharField(max_length=250, verbose_name='Cidade')),
                ('vacina', models.IntegerField(choices=[(1, 'Astrazeneca'), (2, 'Pfizer'), (3, 'Jhonson'), (4, 'Covaxin')], verbose_name='Vacina')),
                ('local_primeira_vacina', models.IntegerField(choices=[(1, 'UFPI'), (2, 'HU'), (3, 'Zona sul'), (4, 'Zona norte'), (5, 'Zona Leste'), (6, 'Centro')], verbose_name='Local primeira vacina')),
                ('data_primeira_vacina', models.DateTimeField(verbose_name='Data e hora primeira vacina')),
                ('hora_primeira_vacina', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], verbose_name='Horário primeira vacina')),
                ('local_segunda_vacina', models.IntegerField(blank=True, choices=[(1, 'UFPI'), (2, 'HU'), (3, 'Zona sul'), (4, 'Zona norte'), (5, 'Zona Leste'), (6, 'Centro')], null=True, verbose_name='Local segunda vacina')),
                ('data_segunda_vacina', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora segunda vacina')),
                ('hora_segunda_vacina', models.IntegerField(blank=True, choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], null=True, verbose_name='Horário segunda vacina')),
            ],
            options={
                'verbose_name': 'Vacina agendada',
                'verbose_name_plural': 'Vacinas agendadas',
            },
        ),
    ]
