# Generated by Django 3.2.6 on 2021-08-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome do paciente')),
                ('cpf', models.CharField(max_length=250, verbose_name='Informe seu CPF ')),
                ('grupo_prioritario', models.IntegerField(choices=[(1, 'Pessoas com 60 anos ou mais institucionalizadas'), (2, 'Pessoas com Deficiência Institucionalizadas'), (3, 'Povos indígenas Vivendo em Terras Indígenas'), (4, 'Trabalhadores de Saúde'), (5, 'Pessoas de 90 anos ou mais'), (6, 'Profissionais da educação')], verbose_name='Informe o grupo Prioritário')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='E-mail')),
                ('data_nascimento', models.DateField(verbose_name='Data Nascimento')),
                ('celular', models.CharField(max_length=250, verbose_name='Núm. celular')),
                ('vacina', models.IntegerField(choices=[(1, 'Astrazeneca'), (2, 'Pfizer'), (3, 'Jhonson'), (4, 'Covaxin')], verbose_name='Vacina')),
                ('local_vacina', models.IntegerField(choices=[(1, 'UFPI'), (2, 'HU'), (3, 'Zona sul'), (4, 'Zona norte'), (5, 'Zona Leste'), (6, 'Centro')], verbose_name='Local vacina')),
                ('data_vacina', models.DateField(verbose_name='Data vacina')),
                ('hora_vacina', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], verbose_name='Horário vacina')),
            ],
            options={
                'verbose_name': 'Vacina agendada',
                'verbose_name_plural': 'Vacinas agendadas',
            },
        ),
    ]
