# Generated by Django 3.2.6 on 2021-08-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data Nascimento'),
        ),
    ]
