# Generated by Django 3.2.6 on 2021-08-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0002_alter_agendamento_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_nascimento',
            field=models.DateTimeField(verbose_name='Data Nascimento'),
        ),
    ]
