# Generated by Django 3.2.6 on 2021-08-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0004_alter_agendamento_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_primeira_vacina',
            field=models.DateField(verbose_name='Data e hora primeira vacina'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_segunda_vacina',
            field=models.DateField(blank=True, null=True, verbose_name='Data e hora segunda vacina'),
        ),
    ]
